import { MemberCardProps } from "../../../types";

export const config = {
  ceo: {
    id: "1",
    name: "Ram",
    phone: 9998887887,
    email: "ram@gmail.com",
    role: "CEO",
    teamName: "",
  } as MemberCardProps,
  hr: [
    {
      id: "2",
      name: "Raman",
      phone: 9998887887,
      email: "ram@gmail.com",
      role: "Head",
      teamName: "Lords",
    },
    {
      id: "13",
      name: "Abhay",
      phone: 9998887887,
      email: "ram@gmail.com",
      role: "Leader",
      teamName: "Lords",
    },
    {
      id: "3",
      name: "Radha",
      phone: 9998887887,
      email: "ram@gmail.com",
      role: "Member",
      teamName: "Lords",
    },
    {
      id: "4",
      name: "Raman",
      phone: 9998887887,
      email: "ram@gmail.com",
      role: "Leader",
      teamName: "Lords2",
    },
    {
      id: "5",
      name: "Radha",
      phone: 9998887887,
      email: "ram@gmail.com",
      role: "Member",
      teamName: "Lords2",
    },
  ] as MemberCardProps[],
  engineering: [
    {
      id: "6",
      name: "Ramesh",
      phone: 9998887887,
      email: "ram@gmail.com",
      role: "Head",
      teamName: "Geeks",
    },
    {
      id: "7",
      name: "Jerry",
      phone: 9998887887,
      email: "ram@gmail.com",
      role: "Leader",
      teamName: "Geeks1",
    },
    {
      id: "8",
      name: "Rajesh",
      phone: 9998887887,
      email: "ram@gmail.com",
      role: "Member",
      teamName: "Geeks1",
    },
    {
      id: "9",
      name: "Ramesh",
      phone: 9998887887,
      email: "ram@gmail.com",
      role: "Leader",
      teamName: "Geeks",
    },
    {
      id: "10",
      name: "Rajesh",
      phone: 9998887887,
      email: "ram@gmail.com",
      role: "Member",
      teamName: "Geeks",
    },
    {
      id: "16",
      name: "Amar",
      phone: 9998887887,
      email: "ram@gmail.com",
      role: "Member",
      teamName: "Geeks",
    },
    {
      id: "17",
      name: "Aman",
      phone: 9998887887,
      email: "ram@gmail.com",
      role: "Member",
      teamName: "Geeks",
    },
  ] as MemberCardProps[],
  design: [
    {
      id: "11",
      name: "Raju",
      phone: 9998887887,
      email: "ram@gmail.com",
      role: "Head",
      teamName: "Falcons",
    },
    {
      id: "14",
      name: "Sumit",
      phone: 9998887887,
      email: "ram@gmail.com",
      role: "Leader",
      teamName: "Falcons",
    },
    {
      id: "12",
      name: "Rajnesh",
      phone: 9998887887,
      email: "ram@gmail.com",
      role: "Member",
      teamName: "Falcons",
    },
  ] as MemberCardProps[],
};
